### ISSUE TITLE
'pupl_UI_evar_add' is not recognized for reading event variables from event names

### ISSUE THREAD

**Issue by SophieSerrarens** [kinleyid/pupillometry-pipeline#37]
Hi, I was testing the code, using the example data to later use this for my own dataset. However, when I try to carry out part A.5.1, I get an error message saying I cannot read event variables form event names because I get this error message: 
"Unrecognized function or variable 'pupl_UI_evar_add' ".

I have tried to find the function in the code files, but could not find it there either. How can I work around this, because I do need this function for my own data set? Thank you!

This is for Matlab version R2023b by the way

**Comment by SophieSerrarens** [comment]
This is for Matlab version R2023b by the way and the full error message is:

**Comment by SophieSerrarens** [comment]
this is the full error message:

Unrecognized function or variable 'pupl_UI_evar_add'.

Error in pupl_evar_add>getargs (line 86)
            pupl_UI_evar_add(EYE, 'sel', args.sel, 'type', 're', 'prompt', 'Read event variables');

Error in pupl_feval (line 28)
                args = getargs(EYE, varargin{:});

Error in pupl_UI_procwrap>@()pupl_feval(func,getactivedata,varargin{:}) (line 18)
updateactivedata(@() pupl_feval(func, getactivedata, varargin{:}), timeline_txt);

Error in updateglobals (line 23)
    [outputs{:}] = feval(func);

Error in updateactivedata (line 4)
updateglobals(getactiveidx, func, 1, true, varargin{:});

Error in pupl_UI_procwrap (line 18)
updateactivedata(@() pupl_feval(func, getactivedata, varargin{:}), timeline_txt);

Error in pupl_UI>@(src,event)pupl_UI_procwrap(@pupl_evar_add,'method','re') (line 401)
        pupl_UI_procwrap(@pupl_evar_add, 'method', 're'));
 
Error while evaluating Menu Callback.

**Comment by kinleyid** [comment]
Thanks for catching this! It should be fixed in https://github.com/kinleyid/PuPl/commit/6f618cc948f652c059e6aa11b39678151a4784a7. `pupl_UI_evar_add` was an experimental function that wasn't meant to be public yet.
